name: build_image_poi
on:
  push:
#    paths:
#      - "apis/poi/**"

#defaults:
#  run:
#    working-directory: apis/poi/web

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ACR build
        id: acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          registry: ${{ secrets.registry }}
          repository: devopsoh
          image: api-poi
          folder: apis/poi/web
          tag: ${{ github.sha }}