name: poi-ci

on:
  push:
    paths:
      - 'apis/poi/**'
  pull_request:
    paths:
      - 'apis/poi/**'

defaults:
  run:
    working-directory: apis/poi

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 3.1
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: apis/poi/tests/UnitTests
      - if: ${{failure() }}
        uses: nashmaniac/create-issue-action@v1.1
        name: Create Issue Action
        with:
          title: Build Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: worflow-failed
          body: Workflow failed for commit ${{github.sha}}