name: build_image_trips
on:
  push:
    branches: [main]
    paths:
      - "apis/trips/**"



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ACR build
        id: acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          registry: ${{ secrets.registry }}
          repository: devopsoh
          image: api-trips
          folder: apis/trips
          tag: ${{ github.sha }}
          branch: main
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'openhackew34zd68trips'
          images: 'openhackew34zd68acr.azurecr.io/devopsoh/api-trips:${{ github.sha }}'