name: build_image_userprofile
on:
  push:
    paths:
      - "apis/userprofile/**"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ACR build
        id: acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          registry: ${{ secrets.registry }}
          repository: devopsoh
          image: api-userprofile
          folder: apis/userprofile
          tag: ${{ github.sha }}
          branch: main